---
metadata:
  name: Remilia Docs
  short_name: Remilia
  description: Remilia - NFT Art Collective
  language: en
  pathPrefix: "/"
  siteImage:
  favicon: "/assets/favicon.png"
  themeColor: "#FFFF00"
header:
  enabled: true
  logo: "/assets/code.svg"
  logoLink: "/"
  helpUrl: ""
  links:
    - text: Homepage
      link: https://remilia.org
      external: true
    - text: Docs
      link: "/"
      external: false
    - text: Market
      link: https://remilia.org
    - text: Chat
      link: https://chat.remilia.org
    - text: TCG Wiki
      link: https://remilia.fandom.com/
sidebar:
  enabled: true
  # forcedNavorder:
  #   - "/introduction"
  #   - "/configuration/basic"
  #   - "/configuration/advanced"
  # expanded:
  groups:
    - order: 1
      path: "/collective"
      title: "Remilia Collective"
    - order: 2
      path: "/investment_scheme"
      title: "Investment Scheme"
    - order: 3
      path: "/market"
      title: "Remilia Market"
    - order: 4
      path: "/projects"
      title: "Remilia Projects"
    - order: 5
      path: "/contract"
    - order: 6
      path: "/community"
      title: "Remilia Community"
  links:
    - text: Homepage
      link: https://remilia.org
    - text: Market
      link: https://remilia.org
    - text: Chat
      link: https://chat.remilia.org
  ignoreIndex: false
pwa:
  enabled: true
  manifest:
    display: standalone
    crossOrigin: anonymous
    icon: "/assets/favicon.png"

# social:
#   twitter: https://twitter.com/remiliacorp

features:
  darkMode:
    enabled: false  
    default: false
  editOnRepo:
    location: https://github.com/remiliacorp/remi-docs 
    type: github
    editable: false
  mermaid:
    language: "mermaid"
    theme: "dark"
    options:
    width: 400
    height: 300
  pageProgress:
    enabled: true
    includePaths:
      - "/configuration/settingup/features"
    excludePaths:
      - "/"
    height: 3
    prependToBody: false
    color: "#A05EB5"
  previousNext:
    enabled: true
    arrowKeyNavigation: true
  propagateNetlifyEnv: true
  rss:
    enabled: true
    title: Remilia Docs
    showIcon: false
    copyright: "2021, Remilia Corp"
    webMaster: "Remilia Corp"
    managingEditor: "Remilia Corp"
    categories:
      - Docs as Code
    ttl: 60
    matchRegex: "^/"
    outputPath: "/rss.xml"
    generator: "boogi"
  scrollTop: true
  search:
    enabled: true
    engine: 'algolia'
    placeholder: 'Search'
    startComponent: 'input' # icon
    excerptSize: 8000
    debounceTime: 380
    snippetLength: 23
    hitsPerPage: 10
    showStats: true
    pagination:
      enabled: true
      totalPages: 10
      showPrevious: true
      showNext: true
  showMetadata: true
  toc:
    show: true
    depth: 4
  fullScreenMode: 
    enabled: false
    hideHeader: true
    hideToc: true
    hideSidebar: true
